etudiant_agenda:
    resource: "@EtudiantAgendaBundle/Controller/"
    type:     annotation
    prefix:   /

crous_grenoble_menu:
    resource: "@CrousGrenobleMenuBundle/Controller/"
    type:     annotation
    prefix:   /

univ_savoie_edt:
    resource: "@UnivSavoieEdtBundle/Controller/"
    type:     annotation
    prefix:   /

